/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_thlt_java;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ForgotPasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordForm
     */
    public ForgotPasswordForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsernameDisplay = new javax.swing.JLabel();
        txtUsernameForget = new javax.swing.JTextField();
        btnFindAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsernameDisplay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUsernameDisplay.setText("Tên đăng nhập");

        txtUsernameForget.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsernameForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameForgetActionPerformed(evt);
            }
        });

        btnFindAccount.setText("Tìm kiếm");
        btnFindAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblUsernameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121)
                .addComponent(txtUsernameForget, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnFindAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsernameDisplay)
                    .addComponent(txtUsernameForget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnFindAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameForgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameForgetActionPerformed

    private void btnFindAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindAccountActionPerformed
        String username = txtUsernameForget.getText();

        // Kiểm tra tên đăng nhập không rỗng
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập.", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return; // Dừng xử lý
        }

        // --- BƯỚC KIỂM TRA TÊN ĐĂNG NHẬP TRONG CSDL ---
        // Câu lệnh SQL để đếm số dòng có tên đăng nhập khớp
        String sql = "SELECT COUNT(*) FROM accounts WHERE username = ?";

        // Sử dụng try-with-resources để quản lý kết nối và PreparedStatement an toàn
        try (Connection con = KN.KNDL(); // Lấy kết nối từ class KN
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, username); // Gán tên đăng nhập vào tham số (?)

            try (ResultSet rs = pst.executeQuery()) { // Thực thi truy vấn và lấy kết quả
                if (rs.next()) {
                    int count = rs.getInt(1); // Lấy giá trị cột đầu tiên (COUNT)

                    if (count > 0) {
                        // --- Tên đăng nhập TỒN TẠI ---
                        // *** CẢNH BÁO BẢO MẬT ***
                        // Đây là điểm yếu của quy trình đơn giản này:
                        // Ngay lập tức cho phép đặt lại mật khẩu mới mà KHÔNG CẦN BƯỚC XÁC MINH THÊM.

                        // Mở form đặt lại mật khẩu mới và TRUYỀN tên đăng nhập sang
                        SetNewPasswordForm setNewPasswordForm = new SetNewPasswordForm(username);
                        setNewPasswordForm.setVisible(true);
                        setNewPasswordForm.setLocationRelativeTo(null);

                        // Đóng form hiện tại (ForgotPasswordForm)
                        this.dispose();

                    } else {
                        // --- Tên đăng nhập KHÔNG TỒN TẠI ---
                        JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        // Tùy chọn: Xóa nội dung trường nhập
                        // txtUsernameForget.setText("");
                    }
                }
            } // ResultSet tự đóng

        } catch (SQLException e) {
            // Bắt và xử lý lỗi CSDL (kết nối, cú pháp SQL, v.v.)
            JOptionPane.showMessageDialog(this, "Lỗi CSDL khi tìm tài khoản: " + e.getMessage(), "Lỗi Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // In chi tiết lỗi ra console
        }
    }//GEN-LAST:event_btnFindAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindAccount;
    private javax.swing.JLabel lblUsernameDisplay;
    private javax.swing.JTextField txtUsernameForget;
    // End of variables declaration//GEN-END:variables
}
